name: Release
on:
  create:
    tags:
    - v*

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: build with pyinstaller
      run: |
        pyinstaller -F -w --uac-admin --version-file ./static/version-info.txt -i ./static/nextcloud-uploader.ico ./nextcloud-uploader.py --hidden-import plyer.platforms.win.notification
    - name: sha256sum
      run: |
        sha256sum nextcloud-uploader.zip | awk '{print $1}' > nextcloud-uploader.zip.sha256
    - name: zip win artifact
      run: |
        powershell Compress-Archive -LiteralPath dist/nextcloud-uploader.exe,static/nextcloud-uploader.ico  -DestinationPath nextcloud-uploader.zip 
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          nextcloud-uploader.zip
          nextcloud-uploader.zip.sha256